baseURL = 'https://sukwonyun.github.io/'
languageCode = 'en-us'
title = "Sukwon Yun"
theme = 'dario'
copyright = 'Webpage template borrows from <a href="https://darioamodei.com/">Dario Amodei</a>.'

mainSections = ['blogs']

[pagination]
  pagerSize = 10

[params]
  description = "Sukwon Yun - PhD student at UW."
  colorScheme = "light"
  katex = true

  [params.author]
    name = "Sukwon Yun"
    email = "sukwon@cs.washington.edu"
    twitter = "@sukwon_yun"

[markup]
  [markup.highlight]
    style = "monokai"
    codeFences = true
    guessSyntax = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['$$', '$$']]
      inline = [['$', '$']]

[taxonomies]
  tag = "tags"
